[project]
name = "httpet"
version = "0.1.0"
description = "Await a pet."
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "aiohttp[speedups]>=3.11.13",
    "pydantic-settings>=2.8.1",
]
